-- 金敦医疗器械进销存系统 - 数据库初始化 SQL
-- 适用于 MySQL 5.7+ / TiDB / PlanetScale / Neon (MySQL 兼容)

-- 系统账号表
CREATE TABLE IF NOT EXISTS `system_accounts` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `username` VARCHAR(64) NOT NULL UNIQUE,
  `password` VARCHAR(256) NOT NULL,
  `createdAt` TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  `updatedAt` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL
);

-- 产品表
CREATE TABLE IF NOT EXISTS `products` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `name` VARCHAR(256) NOT NULL,
  `spec` VARCHAR(256) NOT NULL,
  `unit` VARCHAR(64) NOT NULL,
  `supplier` VARCHAR(256) NOT NULL,
  `purchasePrice` DECIMAL(12,2) NOT NULL,
  `remark` TEXT,
  `status` ENUM('active','disabled') DEFAULT 'active' NOT NULL,
  `createdAt` TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  `updatedAt` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL
);

-- 客户表
CREATE TABLE IF NOT EXISTS `customers` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `name` VARCHAR(256) NOT NULL,
  `warehouseAddress` VARCHAR(512) NOT NULL,
  `contactPerson` VARCHAR(128),
  `status` ENUM('active','disabled') DEFAULT 'active' NOT NULL,
  `createdAt` TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  `updatedAt` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL
);

-- 进货订单表
CREATE TABLE IF NOT EXISTS `purchase_orders` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `orderNo` VARCHAR(32) NOT NULL UNIQUE,
  `totalAmount` DECIMAL(14,2) NOT NULL DEFAULT 0,
  `createdAt` TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  `updatedAt` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL
);

-- 进货订单明细表
CREATE TABLE IF NOT EXISTS `purchase_order_items` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `orderId` INT NOT NULL,
  `productId` INT NOT NULL,
  `productName` VARCHAR(256) NOT NULL,
  `spec` VARCHAR(256) NOT NULL,
  `unit` VARCHAR(64) NOT NULL,
  `supplier` VARCHAR(256) NOT NULL,
  `purchasePrice` DECIMAL(12,2) NOT NULL,
  `quantity` INT NOT NULL,
  `batchNo` VARCHAR(128) NOT NULL,
  `productionDate` VARCHAR(20) NOT NULL,
  `expiryDate` VARCHAR(20) NOT NULL,
  `subtotal` DECIMAL(14,2) NOT NULL,
  `createdAt` TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- 销售订单表
CREATE TABLE IF NOT EXISTS `sales_orders` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `orderNo` VARCHAR(32) NOT NULL UNIQUE,
  `customerId` INT NOT NULL,
  `customerName` VARCHAR(256) NOT NULL,
  `totalAmount` DECIMAL(14,2) NOT NULL DEFAULT 0,
  `totalCost` DECIMAL(14,2) NOT NULL DEFAULT 0,
  `totalTax` DECIMAL(14,2) NOT NULL DEFAULT 0,
  `profit` DECIMAL(14,2) NOT NULL DEFAULT 0,
  `profitRate` DECIMAL(8,2) NOT NULL DEFAULT 0,
  `itemCount` INT NOT NULL DEFAULT 0,
  `createdAt` TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  `updatedAt` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL
);

-- 销售订单明细表
CREATE TABLE IF NOT EXISTS `sales_order_items` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `orderId` INT NOT NULL,
  `productId` INT NOT NULL,
  `productName` VARCHAR(256) NOT NULL,
  `spec` VARCHAR(256) NOT NULL,
  `unit` VARCHAR(64) NOT NULL,
  `supplier` VARCHAR(256) NOT NULL,
  `purchasePrice` DECIMAL(12,2) NOT NULL,
  `batchNo` VARCHAR(128) NOT NULL,
  `quantity` INT NOT NULL,
  `salePrice` DECIMAL(12,2) NOT NULL,
  `taxRate` DECIMAL(5,2) NOT NULL,
  `subtotal` DECIMAL(14,2) NOT NULL,
  `taxAmount` DECIMAL(14,2) NOT NULL,
  `cost` DECIMAL(14,2) NOT NULL,
  `profit` DECIMAL(14,2) NOT NULL,
  `createdAt` TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- 库存表
CREATE TABLE IF NOT EXISTS `inventory` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `productId` INT NOT NULL,
  `productName` VARCHAR(256) NOT NULL,
  `spec` VARCHAR(256) NOT NULL,
  `unit` VARCHAR(64) NOT NULL,
  `supplier` VARCHAR(256) NOT NULL,
  `batchNo` VARCHAR(128) NOT NULL,
  `productionDate` VARCHAR(20) NOT NULL,
  `expiryDate` VARCHAR(20) NOT NULL,
  `quantity` INT NOT NULL DEFAULT 0,
  `inboundDate` TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  `createdAt` TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  `updatedAt` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL
);

-- 初始管理员账号（用户名: jindun，密码: 000000）
INSERT IGNORE INTO `system_accounts` (`username`, `password`) VALUES ('jindun', '000000');
